package org.example;

import org.hyperledger.fabric.gateway.*;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.util.concurrent.TimeoutException;

public class App {
    public static void main(String[] args) throws Exception {
        // Load a CCP (connection profile) generated by the test-network
        Path networkConfigPath = Paths.get("..", "organizations", "peerOrganizations", "org1.example.com", "connection-org1.json");
        if (!Files.exists(networkConfigPath)) {
            System.err.println("Connection profile not found: " + networkConfigPath.toString());
            System.exit(1);
        }

        // Wallet path where test-network stores identities (network.sh can create 'wallet' or you'll run addOrg1User script)
        Path walletPath = Paths.get("wallet");
        Wallet wallet = Wallets.newFileSystemWallet(walletPath);

        if (!wallet.get("appUser").isPresent()) {
            System.err.println("Wallet identity 'appUser' not found. Run the test-network 'addOrg1User' helper or import credentials into the wallet.");
            System.exit(1);
        }

        // Create a gateway connection
        Gateway.Builder builder = Gateway.createBuilder()
            .identity(wallet, "appUser")
            .networkConfig(networkConfigPath)
            .discovery(true);

        try (Gateway gateway = builder.connect()) {
            Network network = gateway.getNetwork("mychannel");
            Contract contract = network.getContract("carauction");

            System.out.println("-> createCar CAR1");
            contract.submitTransaction("createCar", "CAR1", "Toyota", "Corolla", "org1-admin");
            System.out.println("   created");

            System.out.println("-> startAuction CAR1 1000");
            contract.submitTransaction("startAuction", "CAR1", "1000");
            System.out.println("   started");

            System.out.println("-> placeBid CAR1 1200");
            contract.submitTransaction("placeBid", "CAR1", "1200");
            System.out.println("   bid placed");

            System.out.println("-> queryCar CAR1");
            byte[] result = contract.evaluateTransaction("queryCar", "CAR1");
            System.out.println("   Car state: " + new String(result));

            System.out.println("-> finalizeAuction CAR1");
            try {
                byte[] res = contract.submitTransaction("finalizeAuction", "CAR1");
                System.out.println("   Finalize result: " + new String(res));
            } catch (ContractException | TimeoutException e) {
                System.out.println("   Finalize failed (likely owner mismatch): " + e.getMessage());
            }

        }
    }
}
